#!/usr/bin/env bash

set -e

info () {
  printf "\033[95m$1\n"
}

read -p "Enter YAML file(s) to run, to use default press RETURN: " DEFAULT_CONFIG_PREFIX
DEFAULT_CONFIG_PREFIX=${DEFAULT_CONFIG_PREFIX:-default}

CONFIG_SUFFIX=".conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

for conf in ${DEFAULT_CONFIG_PREFIX} ${@}; do
    info "Executing: ${conf}${CONFIG_SUFFIX}"
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${conf}${CONFIG_SUFFIX}"
done
