" MacVim GUI mode
if has("gui_macvim")
   let s:uname = system("uname")
   if s:uname == "Darwin\n"
      set guifont=Inconsolata\ for\ Powerline:h15
   endif

  " resize current buffer by +/- 5
  nnoremap <M-Right> :vertical resize +5<CR>
  nnoremap <M-Left> :vertical resize -5<CR>
  nnoremap <M-Up> :resize -5<CR>
  nnoremap <M-Down> :resize +5<CR>

  " Command+Option+Right for next
  map <D-M-Right> :tabn<CR>
  " Command+Option+Left for previous
  map <D-M-Left> :tabp<CR>

  " Automatically resize splits when resizing MacVim window
  autocmd VimResized * wincmd =
endif

if has("gui_running")
endif
