" Map leader
let mapleader=","
let g:mapleader=","

" Set to auto read when the file is changed outside of VIM (helpful since I
" hybrid between VIM and Sublime
set autoread

" Load bundles
if filereadable(expand('~/.vimrc.bundles'))
  source ~/.vimrc.bundles
endif

if filereadable(expand('~/.vimrc.local'))
  source ~/.vimrc.local
endif


