#!/bin/bash

cd "$(dirname "$0")/.."

# zsh
[ ! -d "$HOME/.oh-my-zsh" ] && curl -L http://install.ohmyz.sh | sh

# OSX
[ "$(uname -s)" == "Darwin" ] && scripts/ox-brew

# UBUNTU
[ "$(uname -s)" != "Darwin" ] && scripts/ubuntu

# switch shell to zsh
if [ $SHELL != '/bin/zsh' ]; then
  sudo chsh -s /bin/zsh
fi
