#!/usr/bin/env bash

info () {
  printf "  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

# Terminator
sudo apt-get install terminator

# Ruby
sudo apt-get update
sudo apt-get install git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev

# RBenv
if [ ! -d "$HOME/.rbenv" ]; then
  cd
  git clone git://github.com/sstephenson/rbenv.git .rbenv
  git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
  git clone https://github.com/sstephenson/rbenv-gem-rehash.git ~/.rbenv/plugins/rbenv-gem-rehash

  rbenv install 2.2.1
  rbenv global 2.2.1
  ruby -v
else
  info '.rbenv already exists!'
fi

# Node
if [ ! -d "$HOME/.npm" ]; then
  sudo add-apt-repository ppa:chris-lea/node.js
  sudo apt-get update
  sudo apt-get install nodejs
else
  info '.npm already exists!'
fi

# Rails
if [ "gem list rails -i" ]; then
  gem install rails -v 4.2.0
  rbenv rehash
  rails -v
else
  info 'rails is already installed!'
fi

# tmux zsh vim ack
sudo apt-get install build-essential tmux zsh vim ack
